// Theme
export const SUCCESS_CODE = 0;
export const FAIL_CODE = -1;

export const THEME_SET = "THEME_SET";
export const THEMES = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  LIGHT: "LIGHT",
  BLUE: "BLUE",
  GREEN: "GREEN",
  INDIGO: "INDIGO",
};

//common
export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_FAILURE = "DATA_FAILURE";

// Auth
export const AUTH_SIGN_UP_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_GET_INFO_REQUEST = "AUTH_GET_INFO_REQUEST";
export const AUTH_GET_INFO_SUCCESS = "AUTH_GET_INFO_SUCCESS";
export const AUTH_GET_INFO_FAILURE = "AUTH_GET_INFO_FAILURE";


export const AUTH_CHECK_ID_REQUEST = "AUTH_CHECK_ID_REQUEST";
export const AUTH_CHECK_ID_SUCCESS = "AUTH_CHECK_ID_SUCCESS";
export const AUTH_CHECK_ID_FAILURE = "AUTH_CHECK_ID_FAILURE";

export const AUTH_FIND_ID_REQUEST = "AUTH_FIND_ID_REQUEST";
export const AUTH_FIND_ID_SUCCESS = "AUTH_FIND_ID_SUCCESS";
export const AUTH_FIND_ID_FAILURE = "AUTH_FIND_ID_FAILURE";

export const AUTH_SMS_VALIDATE_REQUEST = "AUTH_SMS_VALIDATE_REQUEST";
export const AUTH_SMS_VALIDATE_SUCCESS = "AUTH_SMS_VALIDATE_SUCCESS";
export const AUTH_SMS_VALIDATE_FAILURE = "AUTH_SMS_VALIDATE_FAILURE";


export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";

export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

// Member
export const MEMBER_UPDATE_RESET = "MEMBER_UPDATE_RESET";
export const MEMBER_UPDATE_REQUEST = "MEMBER_UPDATE_REQUEST";
export const MEMBER_UPDATE_SUCCESS = "MEMBER_UPDATE_SUCCESS";
export const MEMBER_UPDATE_FAILURE = "MEMBER_UPDATE_FAILURE";

//Group
export const GROUP_LIST_REQUEST = "GROUP_LIST_REQUEST";
export const GROUP_LIST_SUCCESS = "GROUP_LIST_SUCCESS";
export const GROUP_LIST_FAILURE = "GROUP_LIST_FAILURE";



//SMS
export const SMS_SEND_REQUEST = "SMS_SEND_REQUEST";
export const SMS_SEND_SUCCESS = "SMS_SEND_SUCCESS";
export const SMS_SEND_FAILURE = "SMS_SEND_FAILURE";

