// Theme
export const SUCCESS_CODE = 0;
export const FAIL_CODE = -1;

export const THEME_SET = "THEME_SET";
export const THEMES = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  LIGHT: "LIGHT",
  BLUE: "BLUE",
  GREEN: "GREEN",
  INDIGO: "INDIGO",
};

// Auth

export const AUTH_SIGN_UP_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_GET_INFO_REQUEST = "AUTH_GET_INFO_REQUEST";
export const AUTH_GET_INFO_SUCCESS = "AUTH_GET_INFO_SUCCESS";
export const AUTH_GET_INFO_FAILURE = "AUTH_GET_INFO_FAILURE";

export const AUTH_FIND_ID_REQUEST = "AUTH_FIND_ID_REQUEST";
export const AUTH_FIND_ID_SUCCESS = "AUTH_FIND_ID_SUCCESS";
export const AUTH_FIND_ID_FAILURE = "AUTH_FIND_ID_FAILURE";

export const AUTH_SEND_SMS_REQUEST = "AUTH_SEND_SMS_REQUEST";
export const AUTH_SEND_SMS_SUCCESS = "AUTH_SEND_SMS_SUCCESS";
export const AUTH_SEND_SMS_FAILURE = "AUTH_SEND_SMS_FAILURE";


export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";

export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

// Member

export const MEMBER_UPDATE_REQUEST = "MEMBER_UPDATE_REQUEST";
export const MEMBER_UPDATE_SUCCESS = "MEMBER_UPDATE_SUCCESS";
export const MEMBER_UPDATE_FAILURE = "MEMBER_UPDATE_FAILURE";
